### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ChWick** [OMMR4all/ommr4all-line-detection#4]
In GitLab by @chwick on Mar 18, 2019, 13:41

Input:

![gray_deskewed](/uploads/404c2efbeff4ba7d3d1999db7c579b2f/gray_deskewed.jpg)

Model:

[line_detection_0.zip](/uploads/1f49528a7f66641c38e4318364bd4e56/line_detection_0.zip)

Report:

```
Traceback (most recent call last):
  File "/home/wick/Documents/Projects/ommr4all-deploy/modules/ommr4all-server/omr/stafflines/detection/experimenter.py", line 235, in <module>
    experimenter.run(args)
  File "/home/wick/Documents/Projects/ommr4all-deploy/modules/ommr4all-server/omr/stafflines/detection/experimenter.py", line 173, in run
    counts, metrics = zip(*map(run_single, train_args))
  File "/home/wick/Documents/Projects/ommr4all-deploy/modules/ommr4all-server/omr/stafflines/detection/experimenter.py", line 109, in run_single
    counts = evaluator.evaluate(args.test_pcgts_files)
  File "/home/wick/Documents/Projects/ommr4all-deploy/modules/ommr4all-server/omr/stafflines/detection/evaluator.py", line 14, in evaluate
    for p in self.predictor.predict(pcgts_files):
  File "/home/wick/Documents/Projects/ommr4all-deploy/modules/ommr4all-server/omr/stafflines/detection/pixelclassifier/predictor.py", line 61, in predict
    for i, (data, r) in enumerate(zip(dataset, predictions)):
  File "/home/wick/Documents/Projects/ommr4all-deploy/ommr4all-venv/lib/python3.6/site-packages/line_segmentation-0.0.1-py3.6.egg/linesegmentation/detection/lineDetection.py", line 110, in detect_advanced
    yield self.detect_staff_lines(data[i])
  File "/home/wick/Documents/Projects/ommr4all-deploy/ommr4all-venv/lib/python3.6/site-packages/line_segmentation-0.0.1-py3.6.egg/linesegmentation/detection/lineDetection.py", line 141, in detect_staff_lines
    staff_list = self.normalize_lines_in_system(staff_list, staff_space_height, img)
  File "/home/wick/Documents/Projects/ommr4all-deploy/ommr4all-venv/lib/python3.6/site-packages/line_segmentation-0.0.1-py3.6.egg/linesegmentation/detection/lineDetector.py", line 224, in normalize_lines_in_system
    minf = interpolate.interp1d(xmi, ymi, fill_value='extrapolate')
  File "/home/wick/Documents/Projects/ommr4all-deploy/ommr4all-venv/lib/python3.6/site-packages/scipy-1.2.0rc2-py3.6-linux-x86_64.egg/scipy/interpolate/interpolate.py", line 543, in __init__
    "least %d entries" % minval)
ValueError: x and y arrays must have at least 2 entries
```

Config:

```python
LineDetectionSettings(
            numLine=4,
            minLength=6,
            lineExtension=True,
            lineSpaceHeight=20,
            targetLineSpaceHeight=10,
            model=model_path,
            post_process=True,
            smooth_lines=2,
            line_fit_distance=1,
            # debug=True, smooth_lines_advdebug=True,
        )
```

**Comment by ChWick** [comment]
In GitLab by @chwick on Mar 18, 2019, 13:43

changed the description

**Comment by ChWick** [comment]
In GitLab by @s331267 on Mar 19, 2019, 10:04

Could not repdroduce the crash!. But the FCN prediction looks kinda weird and so does the lineprediction, too: Had a similiar problem once when i used the wrong settings for the FCN

![h1](/uploads/5d71a7b5743114b12ec69cd91efef7a7/h1.png)![h2](/uploads/104733d7671753cf7caff445048721cd/h2.png)

**Comment by ChWick** [comment]
In GitLab by @chwick on Mar 19, 2019, 10:35

I know that the network was not trained properly, however, the crash should never occur, even on corrupted data. I'd like to use your project only to verify this bug, how can I input this data (what is the command line call?)

**Comment by ChWick** [comment]
In GitLab by @s331267 on Mar 19, 2019, 11:40

The tool is shipped with a predict script. Depending on your environnment setup you can execute it with

line-segmentation-predict --gray ../gray_deskewed.jpg --load ../line_detection_0/best --debug True

**Comment by ChWick** [comment]
In GitLab by @chwick on Mar 19, 2019, 15:15

I can not reproduce this anymore, even in my code....

**Comment by ChWick** [comment]
In GitLab by @chwick on Mar 19, 2019, 15:15

closed
